[tool.poetry]
name = "is"
version = "0.1.0"
description = ""
authors = ["wjw20010814@163.com <wjw20010814@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
